services:
  flutter:
    build:
      context: ./flutter
      dockerfile: Dockerfile
    volumes:
      - ./flutter:/app
      - /tmp/.X11-unix:/tmp/.X11-unix # X11転送
      - $HOME/Android/Sdk:/opt/android-sdk

    network_mode: "host"


    working_dir: /app
    privileged: true
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}

    depends_on:
      - ros2

# X11転送をするとき以下をホスト側で実行
# xhost +local:docker

  ros2:
    build:
      context: ./ros2
      dockerfile: Dockerfile
    volumes:
      - ./ros2:/root/ros_ws
      - /tmp/.X11-unix:/tmp/.X11-unix # X11転送
    working_dir: /root/ros_ws
    tty: true
    privileged: true
    environment:
      - CCACHE_DIR=/root/.ccache
      - PATH="/usr/lib/ccache:$PATH"
      - CCACHE_MAXSIZE=30G
      - DISPLAY=${DISPLAY}
    # ports:
    #   - "9090:9090"
    network_mode: "host"
