services:
  flutter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
      - /tmp/.X11-unix:/tmp/.X11-unix # X11転送

    working_dir: /app
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}

# X11転送をするとき以下をホスト側で実行
# xhost +local:docker

